# Generated by Django 4.2 on 2023-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='historico',
            field=models.CharField(max_length=150),
        ),
    ]
