# Generated by Django 4.2 on 2023-05-02 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=1, help_text='Anexe um arquivo referente documento', upload_to='gestao_documentos/documento/', verbose_name='documento_anexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 16, 13, 24, 390868), help_text='Data da inclusão do documento', verbose_name='documento_data_inclusao_documento'),
        ),
    ]
