# Generated by Django 4.2 on 2023-05-02 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 16, 17, 13, 510815), help_text='Data da inclusão do documento', verbose_name='documento_data_inclusao_documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
