# Generated by Django 4.2 on 2023-05-02 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documento_link_alter_documento_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='data_inclusao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 16, 18, 11, 250676), help_text='Data da inclusão do documento', verbose_name='documento_data_inclusao_documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='link',
            field=models.CharField(blank=True, help_text='Link de vídeo tutorial', max_length=150, null=True),
        ),
    ]
